"""
Database Statistics API endpoint.
Provides health check, statistics, backup, restore, and version info for the database.
"""
import base64
import logging
import json
import os
import subprocess
from datetime import date, datetime, timezone
from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException, Request, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import (
    Date, DateTime, LargeBinary, Uuid,
    and_, delete, func, select, text, update,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID, insert as pg_insert
from typing import Any, Callable, Dict, Iterator, List, Optional, Sequence, Set, Tuple
from uuid import UUID

from database import get_db
from models import (
    Base,
    Organization, ScopedControl, EvidenceTracking,
    User as UserModel, OrganizationMember, Assignment, Comment,
    CommentHistory, EvidenceCollectionTask, Notification,
    System, SystemEvidenceCapability
)
from catalog_models import (
    SCFCatalogControl, SCFCatalogDomain,
    SCFCatalogEvidence, SCFCatalogAssessmentObjective
)
from auth import optional_auth, require_auth, require_admin, require_platform_admin, get_accessible_org_ids, User
from redis_client import get_redis_client
from upgrade_guard import compare_versions
from schemas import DatabaseBackupResponse, DatabaseRestoreRequest, DatabaseRestoreResponse
# The two most destructive endpoints in the platform (full-DB export and
# restore) are rate-limited at the auth tier; #858 re-enables the decorators
# that were parked during Phase 0 debugging. slowapi injects its headers via
# the Response parameter, so both handlers carry one.
from rate_limiting import rate_limit_auth

logger = logging.getLogger(__name__)

router = APIRouter(tags=["database"])


# =============================================================================
# Tenant export/import scope — SINGLE SOURCE OF TRUTH (#872)
# =============================================================================
# The app-level export at GET /database/backup is a PARTIAL, org-to-org TENANT
# MIGRATION tool, NOT a disaster-recovery backup. For a complete backup (every
# table, the keycloak schema, and the MinIO evidence blobs) use
# scripts/backup.sh / scripts/upgrade.sh.
#
# TENANT_EXPORT_TABLES is the ordered set the endpoint serialises (dependency
# order, parents before children). TENANT_SCOPED_EXCLUDED_TABLES enumerates
# every OTHER organisation-scoped table (one carrying an `organization_id`
# column) that is deliberately NOT exported, each with the reason it is out of
# scope. tests/test_tenant_export_honesty.py fails if a new org-scoped model is
# added without being classified into exactly one of these two sets, so the
# export can never silently drift back into masquerading as a full backup.
TENANT_EXPORT_TABLES: Tuple[str, ...] = (
    "organizations",
    "users",
    "organization_members",
    "systems",
    "scoped_controls",
    "evidence_tracking",
    "system_evidence_capabilities",
    "assignments",
    "comments",
    "comment_history",
    "evidence_collection_tasks",
    "notifications",
)

TENANT_SCOPED_EXCLUDED_TABLES: Dict[str, str] = {
    # Secrets & delivery logs — must never travel in a portable export.
    "api_keys": "secret material; not portable between deployments",
    "webhook_endpoints": "contains signing secrets; deployment-local",
    "webhook_deliveries": "delivery log; regenerated by live traffic",
    # Audit / immutable trail — belongs to the source deployment; captured by
    # the whole-DB dump in scripts/backup.sh, not this portable export.
    "audit_log": "append-only audit trail; captured by scripts/backup.sh",
    "audit_engagements": "audit trail; captured by scripts/backup.sh",
    # Evidence & generated artifacts — the blobs live in MinIO and are captured
    # by scripts/backup.sh; their rows are not part of the migration export.
    "evidence_files": "blob metadata; blobs live in MinIO (scripts/backup.sh)",
    "generated_documents": "generated artifacts; re-generated from primary data",
    # Derived / recomputable analytics — rebuilt from the primary tables.
    "control_assessment_composites": "derived from control + evidence state",
    "evidence_assessments": "derived assessment output; recomputable",
    "evidence_validation_results": "derived validation output; recomputable",
    "evidence_window_assessments": "derived assessment output; recomputable",
    "organization_risk_profiles": "derived risk posture; recomputable",
    "risk_assessments": "derived risk output; recomputable",
    "recipe_feedback": "telemetry; not required for a tenant move",
    # CDM corpus — large, derived from source documents by a separate pipeline.
    "cdm_documents": "CDM corpus; rebuilt by the CDM ingest pipeline",
    "cdm_document_chunks": "CDM corpus; rebuilt by the CDM ingest pipeline",
    "cdm_document_intents": "CDM corpus; rebuilt by the CDM ingest pipeline",
    "cdm_mappings": "CDM corpus; rebuilt by the CDM ingest pipeline",
    "cdm_control_proposals": "CDM corpus; rebuilt by the CDM ingest pipeline",
    # Deployment-local configuration / settings.
    "doc_gen_settings": "deployment-local configuration",
    "evidence_health_config": "deployment-local configuration",
    "organization_assurance_policies": "deployment-local configuration",
    "organization_catalog_state": "catalog state; reseeded on startup",
    "system_catalog_templates": "mostly global catalog data reseeded from JSON; org rows hold regenerable AI recipes",
    "organization_framework_selections": "not yet represented in the export set",
    # Cross-org / invitation state — not part of a single-tenant export.
    "consultant_client_relationships": "cross-tenant relationship; not portable",
    "consultant_invites": "invitation state; not portable",
    "organization_invites": "invitation state; not portable",
    "organization_reconciliation_runs": "run history; not required for a move",
    # Teams & team assignments — collaboration tables not yet in the export set.
    "teams": "not yet represented in the export set",
    "team_members": "not yet represented in the export set",
    "control_team_assignments": "not yet represented in the export set",
    "evidence_team_assignments": "not yet represented in the export set",
    # Custom risk register — not yet in the export set.
    "custom_risk_definitions": "not yet represented in the export set",
    "custom_risk_control_mappings": "not yet represented in the export set",
    # Vendors — not yet in the export set.
    "vendors": "not yet represented in the export set",
    "vendor_reports": "not yet represented in the export set",
}


# =============================================================================
# Backup / restore tuning
# =============================================================================

# database.py configures no statement_timeout and no lock_timeout on the engine,
# so a large restore can hold row locks for as long as it likes and wedge every
# other writer. The restore sets both for the duration of its own transaction.
RESTORE_STATEMENT_TIMEOUT_MS = 300_000
RESTORE_LOCK_TIMEOUT_MS = 15_000

# asyncpg rejects a statement carrying more than 32767 bind parameters, so both
# the `IN (...)` reads and the multi-VALUES upserts stay well under that.
ID_CHUNK_SIZE = 5_000
UPSERT_CHUNK_SIZE = 500

# Columns a restore must never take from the payload. is_platform_admin would
# make a hand-edited backup a privilege-escalation vector; oidc_issuer is owned
# by the first-login relink flow in auth.py, and overwriting it breaks the
# identity lookup that authenticates every subsequent request.
USER_PROTECTED_COLUMNS = frozenset({"is_platform_admin", "oidc_issuer"})

# Self-referential foreign key resolved in a second pass once every comment in
# the payload exists, so it is exempt from the first-pass reference guard.
DEFERRED_FK_COLUMNS = frozenset({("comments", "parent_comment_id")})

# Tables restored, in parent-before-child order. The delete-absent sweep walks
# this list in reverse. Neither `users` nor `organizations` appears: users are
# cross-organisation identity rather than tenant data, and deleting an
# organisation cascades across ~30 tables.
RESTORE_DELETE_ORDER = (
    "comment_history",
    "notifications",
    "evidence_collection_tasks",
    "comments",
    "assignments",
    "system_evidence_capabilities",
    "evidence_tracking",
    "systems",
    "scoped_controls",
    "organization_members",
)


def serialize_row(row) -> Dict[str, Any]:
    """Serialize a SQLAlchemy model instance to a JSON-safe dictionary."""
    result = {}
    for column in row.__table__.columns:
        value = getattr(row, column.name)
        if value is None:
            result[column.name] = None
        elif isinstance(value, UUID):
            result[column.name] = str(value)
        elif isinstance(value, (bytes, bytearray, memoryview)):
            # Binary columns (Organization.logo_data) are not JSON encodable:
            # FastAPI's encoder tries to utf-8 decode bytes and raises on any
            # real image, which made the whole backup 500 for an organisation
            # that had uploaded a logo. Base64 is additive — a NULL logo still
            # serialises as null, so v1.1 files written before this stay valid.
            result[column.name] = base64.b64encode(bytes(value)).decode("ascii")
        elif isinstance(value, datetime):
            result[column.name] = value.isoformat()
        elif hasattr(value, 'isoformat'):  # date objects
            result[column.name] = value.isoformat()
        else:
            result[column.name] = value
    return result


def chunked(values: Sequence[Any], size: int) -> Iterator[List[Any]]:
    """Yield successive fixed-size slices of ``values``."""
    for start in range(0, len(values), size):
        yield list(values[start:start + size])


def coerce_column_value(column, value: Any) -> Any:
    """
    Coerce one JSON-decoded backup value to what its column's type expects.

    Driven by the column's declared type rather than by a hand-written mapping,
    so a column added to a model is carried by the next restore automatically.
    """
    if value is None:
        return None

    column_type = column.type

    if isinstance(column_type, (PGUUID, Uuid)):
        return UUID(value) if isinstance(value, str) else value

    if isinstance(column_type, DateTime):
        parsed = value if isinstance(value, datetime) else datetime.fromisoformat(
            str(value).replace("Z", "+00:00")
        )
        # These are `timestamp without time zone` columns and asyncpg refuses an
        # aware datetime for them, so a Z-suffixed or offset-bearing value is
        # normalised to naive UTC rather than failing mid-restore.
        if not column_type.timezone and parsed.tzinfo is not None:
            parsed = parsed.astimezone(timezone.utc).replace(tzinfo=None)
        return parsed

    if isinstance(column_type, Date):
        if isinstance(value, datetime):
            return value.date()
        if isinstance(value, date):
            return value
        return date.fromisoformat(str(value))

    if isinstance(column_type, LargeBinary):
        return base64.b64decode(value) if isinstance(value, str) else value

    return value


def hydrate_row(
    model,
    row: Dict[str, Any],
    exclude: frozenset = frozenset(),
) -> Dict[str, Any]:
    """
    Map a serialized backup row onto every real column the model declares.

    Replaces the hand-written constructors this endpoint used to carry, which
    named a subset of each model's columns and so silently discarded roughly
    fifteen columns on every restore (ScopedControl.control_weighting,
    EvidenceTracking.maturity_level, Organization.settings, and the rest).

    A key absent from the row is left out of the insert entirely rather than
    written as NULL, so columns carrying a server_default keep it.
    """
    values: Dict[str, Any] = {}
    for column in model.__table__.columns:
        if column.name in exclude or column.name not in row:
            continue
        values[column.name] = coerce_column_value(column, row[column.name])
    return values


def foreign_key_targets(model) -> List[Tuple[Any, str, str]]:
    """
    Return ``(column, target_table, target_column)`` for each foreign key.

    Reads ``fk.target_fullname`` rather than ``fk.column``: the latter resolves
    the target Table and raises NoReferencedTableError for tables whose model is
    not imported in this module (systems.catalog_template_id → the catalog
    tables), which would break restore for every model that has one.
    """
    targets: List[Tuple[Any, str, str]] = []
    for column in model.__table__.columns:
        for foreign_key in column.foreign_keys:
            table_name, _, column_name = foreign_key.target_fullname.rpartition(".")
            targets.append((column, table_name, column_name))
    return targets


async def fetch_existing_ids(
    db: AsyncSession,
    table_name: str,
    column_name: str,
    values,
) -> Set[Any]:
    """Return the subset of ``values`` that currently exist in the target table."""
    values = list(values)
    if not values:
        return set()

    # Resolved through the mapper metadata rather than by interpolating the
    # identifiers into a SQL string. ``foreign_key_targets`` cannot use
    # ``fk.column`` because that raises NoReferencedTableError for targets whose
    # model is not imported in this module, but ``Base.metadata.tables`` carries
    # every mapped table including those (verified: all 18 distinct FK targets
    # resolve, catalog tables included). Going through Core also means
    # SQLAlchemy quotes the identifiers instead of this function trusting them.
    table = Base.metadata.tables.get(table_name)
    if table is None or column_name not in table.c:
        raise ValueError(
            f"Refusing to query unknown foreign key target {table_name}.{column_name}"
        )
    target_column = table.c[column_name]

    return set(await fetch_scalars_in(db, target_column, target_column, values))


async def fetch_scalars_in(db: AsyncSession, selected_column, filter_column, values) -> List[Any]:
    """``SELECT selected_column WHERE filter_column IN values``, chunked."""
    values = list(values)
    if not values:
        return []
    found: List[Any] = []
    for chunk in chunked(values, ID_CHUNK_SIZE):
        result = await db.execute(select(selected_column).where(filter_column.in_(chunk)))
        found.extend(row[0] for row in result.fetchall())
    return found


async def fetch_rows_in(db: AsyncSession, model, filter_column, values) -> List[Any]:
    """``SELECT model WHERE filter_column IN values``, chunked."""
    values = list(values)
    if not values:
        return []
    rows: List[Any] = []
    for chunk in chunked(values, ID_CHUNK_SIZE):
        result = await db.execute(select(model).where(filter_column.in_(chunk)))
        rows.extend(result.scalars().all())
    return rows


async def resolve_dangling_references(
    db: AsyncSession,
    model,
    values_list: List[Dict[str, Any]],
) -> Tuple[List[Dict[str, Any]], int, int]:
    """
    Null or drop references whose target row does not exist.

    Backups written before the user-union fix export zero users while their
    rows still carry owner_user_id and assigned_user_id values, so restoring one
    raises a foreign key violation that fails the entire request. A nullable
    reference is nulled — exactly what the ON DELETE SET NULL every one of these
    columns already declares would do — and a row whose NOT NULL parent is
    missing is dropped. Both are counted and returned to the caller so the
    response reports the degradation instead of hiding it.

    Parents restored earlier in the same transaction are visible here because
    the upserts run as Core statements, not pending ORM state.

    Returns ``(kept_values, nulled_count, dropped_count)``.
    """
    if not values_list:
        return values_list, 0, 0

    checked = [
        (column, target_table, target_column)
        for column, target_table, target_column in foreign_key_targets(model)
        if (model.__tablename__, column.name) not in DEFERRED_FK_COLUMNS
    ]
    if not checked:
        return values_list, 0, 0

    resolvable: Dict[str, Set[Any]] = {}
    for column, target_table, target_column in checked:
        referenced = {
            values[column.name]
            for values in values_list
            if values.get(column.name) is not None
        }
        resolvable[column.name] = await fetch_existing_ids(
            db, target_table, target_column, referenced
        )

    kept: List[Dict[str, Any]] = []
    nulled = 0
    dropped = 0
    for values in values_list:
        drop_row = False
        for column, _, _ in checked:
            value = values.get(column.name)
            if value is None or value in resolvable[column.name]:
                continue
            if column.nullable:
                values[column.name] = None
                nulled += 1
            else:
                drop_row = True
                break
        if drop_row:
            dropped += 1
        else:
            kept.append(values)

    if nulled or dropped:
        logger.warning(
            "Restore of %s: nulled %d unresolvable optional reference(s), "
            "dropped %d row(s) whose required parent is missing",
            model.__tablename__, nulled, dropped,
        )
    return kept, nulled, dropped


def group_by_key_signature(values_list: List[Dict[str, Any]]) -> List[List[Dict[str, Any]]]:
    """
    Group rows that name exactly the same columns.

    A multi-VALUES INSERT needs one column list, so rows are grouped instead of
    being padded with NULLs — padding would overwrite a server_default for any
    column an older backup omits.
    """
    groups: Dict[Tuple[str, ...], List[Dict[str, Any]]] = {}
    for values in values_list:
        groups.setdefault(tuple(sorted(values)), []).append(values)
    return list(groups.values())


async def upsert_rows(
    db: AsyncSession,
    model,
    values_list: List[Dict[str, Any]],
    *,
    insert_only: bool = False,
) -> int:
    """
    Insert rows, updating on primary key conflict. Returns the row count the
    database reports, never the length of the payload.

    ``insert_only`` inserts rows that are absent and leaves existing rows
    untouched. It deliberately declares no conflict target: users carry three
    unique constraints (id, email, and (oidc_issuer, google_sub)), and targeting
    only id would let a backup whose user rows were re-keyed raise a duplicate
    email partway through and fail the restore.
    """
    if not values_list:
        return 0

    affected = 0
    for group in group_by_key_signature(values_list):
        for chunk in chunked(group, UPSERT_CHUNK_SIZE):
            statement = pg_insert(model).values(chunk)
            if insert_only:
                statement = statement.on_conflict_do_nothing()
            else:
                updatable = {
                    column.name: statement.excluded[column.name]
                    for column in model.__table__.columns
                    if not column.primary_key and column.name in chunk[0]
                }
                if updatable:
                    statement = statement.on_conflict_do_update(
                        index_elements=["id"], set_=updatable
                    )
                else:
                    # Every column in this group is the primary key, so there is
                    # nothing an update could change.
                    statement = statement.on_conflict_do_nothing(index_elements=["id"])
            result = await db.execute(statement)
            affected += result.rowcount or 0
    return affected


async def delete_rows_by_id(db: AsyncSession, model, ids) -> int:
    """Delete the given primary keys. Returns the row count the database reports."""
    ids = list(ids)
    if not ids:
        return 0
    affected = 0
    for chunk in chunked(ids, ID_CHUNK_SIZE):
        result = await db.execute(delete(model).where(model.id.in_(chunk)))
        affected += result.rowcount or 0
    return affected


def backup_table_rows(data: Dict[str, Any], table: str) -> List[Dict[str, Any]]:
    """Read one table out of a backup payload, rejecting a malformed shape."""
    rows = data.get(table) or []
    if not isinstance(rows, list):
        raise HTTPException(
            status_code=400,
            detail=f"Invalid backup: '{table}' must be a list of rows, got {type(rows).__name__}",
        )
    for row in rows:
        if not isinstance(row, dict):
            raise HTTPException(
                status_code=400,
                detail=f"Invalid backup: '{table}' contains a non-object row",
            )
    return rows


def backup_row_ids(data: Dict[str, Any], table: str) -> Set[UUID]:
    """Collect the primary keys a backup carries for one table."""
    ids: Set[UUID] = set()
    for row in backup_table_rows(data, table):
        raw_id = row.get("id")
        if raw_id is None:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid backup: a row in '{table}' has no 'id'",
            )
        try:
            ids.add(UUID(raw_id) if isinstance(raw_id, str) else raw_id)
        except (ValueError, AttributeError, TypeError) as exc:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid backup: '{table}' row has an unparseable id {raw_id!r}: {exc}",
            )
    return ids


async def admin_scope_org_ids(user: User, db: AsyncSession) -> List[UUID]:
    """
    Organisations a caller of these two endpoints may back up or restore.

    ``auth.get_accessible_org_ids`` answers a deliberately different question:
    which organisations is this user a *member* of, directly or as a consultant.
    Platform admin is a cross-organisation role that carries no memberships of
    its own, so for a real platform admin that accessor returns ``[]`` — which
    would hand the operator HTTP 200 and a backup file containing nothing, and
    would 403 every restore they attempted. Both endpoints are already gated by
    ``require_platform_admin``, so membership is the wrong question to ask here.

    API-key principals keep exactly the scope ``get_accessible_org_ids`` gives
    them. That function refuses to enumerate organisations for a static key
    outside single-tenant mode as an IDOR guard, and widening it here would
    reintroduce the hole it was added to close.
    """
    if user.auth_method in ("api_key", "user_api_key"):
        return list(await get_accessible_org_ids(user, db))

    if user.db_id:
        is_platform_admin = await db.scalar(
            select(UserModel.is_platform_admin).where(UserModel.id == UUID(user.db_id))
        )
        if is_platform_admin:
            result = await db.execute(select(Organization.id))
            return [row[0] for row in result.fetchall()]

    return list(await get_accessible_org_ids(user, db))


def user_fk_column_names(model) -> List[str]:
    """Names of the columns on ``model`` that reference ``users.id``."""
    return [
        column.name
        for column in model.__table__.columns
        if any(fk.target_fullname == "users.id" for fk in column.foreign_keys)
    ]


def collect_referenced_user_ids(model, rows) -> Set[UUID]:
    """
    Gather every users.id value the given ORM rows point at.

    A backup that omits a user one of its own rows references cannot satisfy its
    own foreign keys on restore, which is what made the previous backup export
    zero users whenever organization_members happened to be empty.
    """
    columns = user_fk_column_names(model)
    if not columns:
        return set()
    referenced: Set[UUID] = set()
    for row in rows:
        for column_name in columns:
            value = getattr(row, column_name)
            if value is not None:
                referenced.add(value)
    return referenced


async def backfill_notification_orgs(
    db: AsyncSession,
    rows: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Fill organization_id on notification rows from pre-#852 backups.

    notifications.organization_id is NOT NULL since migration notiforg1, but
    a backup taken before it carries rows without the key — and hydrate_row
    deliberately omits absent keys, so the insert would fail whole. Backups
    only ever include notifications referencing assignables (control /
    evidence / task) and comments (see the backup's scoping above), so the
    org is derived exactly as the migration derived it: from the referenced
    entity, which this restore has just written in earlier steps. Rows whose
    reference cannot be resolved are dropped, mirroring the migration's
    treatment of orphans.
    """
    missing = [r for r in rows if not r.get("organization_id")]
    if not missing:
        return rows

    def ids_for(ref_type: str) -> List[Any]:
        return [r["reference_id"] for r in missing if r.get("reference_type") == ref_type]

    org_by_ref: Dict[str, Any] = {}

    async def load(model, id_col, org_col, ids):
        if not ids:
            return
        result = await db.execute(
            select(id_col, org_col).where(id_col.in_([UUID(str(i)) for i in ids]))
        )
        for row in result.all():
            org_by_ref[str(row[0])] = row[1]

    await load(ScopedControl, ScopedControl.id, ScopedControl.organization_id, ids_for("control"))
    await load(EvidenceTracking, EvidenceTracking.id, EvidenceTracking.organization_id, ids_for("evidence"))
    await load(EvidenceCollectionTask, EvidenceCollectionTask.id, EvidenceCollectionTask.organization_id, ids_for("task"))

    # comment: two hops — comment row -> commentable entity -> org. The
    # commentables are the same three tables, all restored before step 11.
    comment_ids = ids_for("comment")
    if comment_ids:
        comment_result = await db.execute(
            select(Comment.id, Comment.commentable_type, Comment.commentable_id)
            .where(Comment.id.in_([UUID(str(i)) for i in comment_ids]))
        )
        commentables = {"control": [], "evidence": [], "task": []}
        comment_targets = {}
        for cid, ctype, ctarget in comment_result.all():
            comment_targets[str(cid)] = (ctype, str(ctarget))
            if ctype in commentables:
                commentables[ctype].append(ctarget)
        target_org: Dict[str, Any] = {}

        async def load_target(model, ids):
            if not ids:
                return
            result = await db.execute(
                select(model.id, model.organization_id).where(model.id.in_(ids))
            )
            for row in result.all():
                target_org[str(row[0])] = row[1]

        await load_target(ScopedControl, commentables["control"])
        await load_target(EvidenceTracking, commentables["evidence"])
        await load_target(EvidenceCollectionTask, commentables["task"])
        for cid, (ctype, ctarget) in comment_targets.items():
            org = target_org.get(ctarget)
            if org is not None:
                org_by_ref[cid] = org

    kept: List[Dict[str, Any]] = []
    dropped = 0
    for r in rows:
        if r.get("organization_id"):
            kept.append(r)
            continue
        org = org_by_ref.get(str(r.get("reference_id")))
        if org is None:
            dropped += 1
            continue
        r = dict(r)
        r["organization_id"] = str(org)
        kept.append(r)

    if dropped:
        logger.warning(
            f"Restore: dropped {dropped} pre-#852 notification rows whose "
            f"reference could not be resolved to an organization"
        )
    return kept


def coerce_uuid(value: Any) -> Optional[UUID]:
    """Best-effort parse of a backup value into a UUID, or None.

    Payload ids arrive as strings; an already-parsed UUID passes through and an
    unparseable value becomes None rather than raising, so callers building a
    scope set treat a malformed reference the same as a missing one — out of
    scope — instead of failing the whole restore.
    """
    if value is None:
        return None
    if isinstance(value, UUID):
        return value
    try:
        return UUID(str(value))
    except (ValueError, AttributeError, TypeError):
        return None


async def restore_table(
    db: AsyncSession,
    model,
    rows: List[Dict[str, Any]],
    *,
    exclude: frozenset = frozenset(),
    overrides: Optional[Dict[str, Any]] = None,
    insert_only: bool = False,
    scope_predicate: Optional[Callable[[Dict[str, Any]], bool]] = None,
) -> Tuple[int, int, int]:
    """
    Hydrate, reference-check and upsert one table's rows.

    ``scope_predicate`` is the cross-tenant write guard (#870): when given, a
    hydrated row it rejects is dropped before the upsert and counted into the
    returned ``dropped_rows`` — so an out-of-scope row is reported through the
    same ``skipped_rows`` channel as a row whose required parent was missing,
    never silently swallowed.

    Returns ``(upserted, nulled_references, dropped_rows)``.
    """
    values_list = []
    out_of_scope = 0
    for row in rows:
        values = hydrate_row(model, row, exclude)
        if "id" not in values:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid backup: a row in '{model.__tablename__}' has no 'id'",
            )
        if overrides:
            values.update(overrides)
        if scope_predicate is not None and not scope_predicate(values):
            out_of_scope += 1
            continue
        values_list.append(values)

    values_list, nulled, dropped = await resolve_dangling_references(db, model, values_list)
    upserted = await upsert_rows(db, model, values_list, insert_only=insert_only)
    return upserted, nulled, dropped + out_of_scope


@router.get("/database/stats")
# @limiter.limit(READ_RATE_LIMIT)  # Temporarily disabled
async def get_database_stats(
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_auth)
):
    """
    Get comprehensive database health and statistics.

    Requires authentication.
    """
    logger.info(f"Database stats accessed by: {current_user.email or current_user.user_id} ({current_user.auth_method})")

    try:
        # Count core tables
        org_count = await db.scalar(select(func.count()).select_from(Organization))
        control_count = await db.scalar(select(func.count()).select_from(ScopedControl))
        evidence_count = await db.scalar(select(func.count()).select_from(EvidenceTracking))

        # Count user persistence tables
        user_count = await db.scalar(select(func.count()).select_from(UserModel))
        org_member_count = await db.scalar(select(func.count()).select_from(OrganizationMember))
        assignment_count = await db.scalar(select(func.count()).select_from(Assignment))
        comment_count = await db.scalar(select(func.count()).select_from(Comment))
        task_count = await db.scalar(select(func.count()).select_from(EvidenceCollectionTask))
        notification_count = await db.scalar(select(func.count()).select_from(Notification))

        # Control statistics
        selected_count = await db.scalar(
            select(func.count()).select_from(ScopedControl).where(ScopedControl.selected == True)
        )

        implemented_count = await db.scalar(
            select(func.count()).select_from(ScopedControl).where(
                ScopedControl.implementation_status == 'implemented'
            )
        )

        at_risk_count = await db.scalar(
            select(func.count()).select_from(ScopedControl).where(
                ScopedControl.implementation_status == 'at_risk'
            )
        )

        # Evidence statistics
        tracked_evidence_count = await db.scalar(
            select(func.count()).select_from(EvidenceTracking).where(
                EvidenceTracking.is_tracked == True
            )
        )

        # Group by implementation status
        status_result = await db.execute(
            select(
                ScopedControl.implementation_status,
                func.count(ScopedControl.id).label('count')
            )
            .where(ScopedControl.implementation_status.isnot(None))
            .group_by(ScopedControl.implementation_status)
        )
        by_status = {row[0]: row[1] for row in status_result}

        # Group by maturity level
        maturity_result = await db.execute(
            select(
                ScopedControl.maturity_level,
                func.count(ScopedControl.id).label('count')
            )
            .where(ScopedControl.maturity_level.isnot(None))
            .group_by(ScopedControl.maturity_level)
        )
        by_maturity = {row[0]: row[1] for row in maturity_result}

        # User statistics
        active_users_count = await db.scalar(
            select(func.count()).select_from(UserModel).where(UserModel.last_login_at.isnot(None))
        )

        # Task statistics
        pending_tasks_count = await db.scalar(
            select(func.count()).select_from(EvidenceCollectionTask).where(
                EvidenceCollectionTask.status != 'completed'
            )
        )

        completed_tasks_count = await db.scalar(
            select(func.count()).select_from(EvidenceCollectionTask).where(
                EvidenceCollectionTask.status == 'completed'
            )
        )

        overdue_tasks_count = await db.scalar(
            select(func.count()).select_from(EvidenceCollectionTask).where(
                and_(
                    EvidenceCollectionTask.status != 'completed',
                    EvidenceCollectionTask.due_date < func.current_date()
                )
            )
        )

        # Group tasks by status
        task_status_result = await db.execute(
            select(
                EvidenceCollectionTask.status,
                func.count(EvidenceCollectionTask.id).label('count')
            )
            .where(EvidenceCollectionTask.status.isnot(None))
            .group_by(EvidenceCollectionTask.status)
        )
        tasks_by_status = {row[0]: row[1] for row in task_status_result}

        # Group tasks by type
        task_type_result = await db.execute(
            select(
                EvidenceCollectionTask.task_type,
                func.count(EvidenceCollectionTask.id).label('count')
            )
            .where(EvidenceCollectionTask.task_type.isnot(None))
            .group_by(EvidenceCollectionTask.task_type)
        )
        tasks_by_type = {row[0]: row[1] for row in task_type_result}

        # Notification statistics
        unread_notifications_count = await db.scalar(
            select(func.count()).select_from(Notification).where(
                Notification.is_read == False
            )
        )

        # Comment statistics
        recent_comments_count = await db.scalar(
            select(func.count()).select_from(Comment).where(
                Comment.is_deleted == False
            )
        )

        # Recent activity
        last_control_update = await db.scalar(
            select(func.max(ScopedControl.updated_at)).select_from(ScopedControl)
        )

        last_evidence_update = await db.scalar(
            select(func.max(EvidenceTracking.updated_at)).select_from(EvidenceTracking)
        )

        # For comments, use created_at (edited_at tracks edits but created_at is the base timestamp)
        last_comment_update = await db.scalar(
            select(func.max(Comment.created_at)).select_from(Comment)
        )

        # For tasks, use created_at (no updated_at field, completed_date is just a date)
        last_task_update = await db.scalar(
            select(func.max(EvidenceCollectionTask.created_at)).select_from(EvidenceCollectionTask)
        )

        return {
            "status": "healthy",
            "database": {
                "organizations": org_count or 0,
                "scoped_controls": control_count or 0,
                "evidence_tracking": evidence_count or 0,
                "users": user_count or 0,
                "organization_members": org_member_count or 0,
                "assignments": assignment_count or 0,
                "comments": comment_count or 0,
                "evidence_collection_tasks": task_count or 0,
                "notifications": notification_count or 0,
                "total_records": (
                    (org_count or 0) + (control_count or 0) + (evidence_count or 0) +
                    (user_count or 0) + (org_member_count or 0) + (assignment_count or 0) +
                    (comment_count or 0) + (task_count or 0) + (notification_count or 0)
                )
            },
            "statistics": {
                "selected_controls": selected_count or 0,
                "implemented_controls": implemented_count or 0,
                "at_risk_controls": at_risk_count or 0,
                "tracked_evidence": tracked_evidence_count or 0,
                "active_users": active_users_count or 0,
                "pending_tasks": pending_tasks_count or 0,
                "completed_tasks": completed_tasks_count or 0,
                "overdue_tasks": overdue_tasks_count or 0,
                "unread_notifications": unread_notifications_count or 0,
                "total_comments": recent_comments_count or 0
            },
            "by_status": by_status,
            "by_maturity": by_maturity,
            "tasks_by_status": tasks_by_status,
            "tasks_by_type": tasks_by_type,
            "recent_updates": {
                "last_control_update": last_control_update.isoformat() if last_control_update else None,
                "last_evidence_update": last_evidence_update.isoformat() if last_evidence_update else None,
                "last_comment_update": last_comment_update.isoformat() if last_comment_update else None,
                "last_task_update": last_task_update.isoformat() if last_task_update else None
            }
        }
    except HTTPException:
        # A status this endpoint chose deliberately; re-raise it unchanged
        # rather than relabelling it 500 below.
        raise
    except Exception as e:
        logger.error(f"Failed to retrieve database statistics: {type(e).__name__}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to retrieve database statistics: {str(e)}"
        )


@router.get("/database/backup")
@rate_limit_auth
async def backup_database(
    request: Request,
    response: Response,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_platform_admin)
):
    """
    Export user data tables to JSON format for backup.

    PLATFORM ADMIN ONLY: Database backups contain sensitive multi-tenant data.
    Only platform administrators can export data.

    Returns a JSON object containing:
    - metadata: version, timestamp, table counts, accessible_organizations
    - data: filtered records from each table

    Tables are exported in dependency order to support proper restoration.

    NOTE: Catalog tables (scf_catalog_*) are NOT included in backups.
    Catalog data is reference data seeded from SCF JSON files on application startup.
    """
    logger.info(f"Database backup initiated by: {current_user.email or current_user.user_id}")

    try:
        # Organisations in scope for this caller. Platform admin is cross-org,
        # so this is not the same question as "which orgs am I a member of".
        accessible_org_ids = await admin_scope_org_ids(current_user, db)

        if not accessible_org_ids:
            # Never hand back 200 plus an empty file. A backup the operator
            # believes they hold and cannot actually restore from is worse than
            # no backup at all, so this fails loudly instead.
            logger.warning(
                "Backup aborted for %s: no organisations in scope",
                current_user.email or current_user.user_id,
            )
            raise HTTPException(
                status_code=409,
                detail=(
                    "Backup aborted: no organisations are in scope for your account, "
                    "so the file would contain no data. Nothing was exported."
                ),
            )

        logger.info(f"Backup scoped to {len(accessible_org_ids)} accessible organisation(s)")

        # Export tables in dependency order, filtered by accessible organisations.
        # Rows are held as ORM objects until the end so the users export can be
        # derived from the foreign keys they actually carry.

        # 1. Root entities - filter by accessible org IDs
        org_rows = await fetch_rows_in(db, Organization, Organization.id, accessible_org_ids)

        # 2. First-level dependencies - filter by accessible org IDs
        member_rows = await fetch_rows_in(
            db, OrganizationMember, OrganizationMember.organization_id, accessible_org_ids
        )

        # Systems (depends on organizations)
        system_rows = await fetch_rows_in(db, System, System.organization_id, accessible_org_ids)
        system_ids = [row.id for row in system_rows]

        # Scoped controls - filter by accessible org IDs
        control_rows = await fetch_rows_in(
            db, ScopedControl, ScopedControl.organization_id, accessible_org_ids
        )
        control_ids = [row.id for row in control_rows]

        # Evidence tracking - filter by accessible org IDs
        evidence_rows = await fetch_rows_in(
            db, EvidenceTracking, EvidenceTracking.organization_id, accessible_org_ids
        )
        evidence_ids = [row.id for row in evidence_rows]

        # System evidence capabilities - filter by system IDs in accessible orgs
        capability_rows = await fetch_rows_in(
            db, SystemEvidenceCapability, SystemEvidenceCapability.system_id, system_ids
        )

        # 3. Second-level dependencies
        # Evidence collection tasks - filter by evidence_tracking_id in accessible orgs.
        # Fetched before assignments and comments because both can legally point
        # at a task, and their scope has to include these ids.
        task_rows = await fetch_rows_in(
            db, EvidenceCollectionTask, EvidenceCollectionTask.evidence_tracking_id, evidence_ids
        )
        task_ids = [row.id for row in task_rows]

        # assignable_type and commentable_type both hold 'control', 'evidence' or
        # 'task'. Omitting the task ids meant task assignments and task comments
        # were never backed up at all, and the restore scope has to agree with
        # this one or it would treat them as absent and delete them.
        accessible_assignable_ids = control_ids + evidence_ids + task_ids

        assignment_rows = await fetch_rows_in(
            db, Assignment, Assignment.assignable_id, accessible_assignable_ids
        )

        comment_rows = await fetch_rows_in(
            db, Comment, Comment.commentable_id, accessible_assignable_ids
        )
        comment_ids = [row.id for row in comment_rows]

        # Notifications - scoped by the entity referenced, not by user_id. A
        # Notification carries only user_id and an untyped reference_id, and a
        # user who belongs to two tenants would otherwise drag the other
        # tenant's notifications into this backup.
        notification_rows = await fetch_rows_in(
            db, Notification, Notification.reference_id, accessible_assignable_ids + comment_ids
        )

        # 4. Third-level dependencies
        # Comment history - filter by comment_id in accessible comments
        history_rows = await fetch_rows_in(
            db, CommentHistory, CommentHistory.comment_id, comment_ids
        )

        # Users: members of accessible organisations, plus every user referenced
        # by a foreign key on any exported row. Exporting only the members left a
        # backup that could not satisfy its own foreign keys, and exported no
        # users at all whenever organization_members was empty.
        exported_user_ids: Set[UUID] = {row.user_id for row in member_rows}
        for model, rows in (
            (Organization, org_rows),
            (OrganizationMember, member_rows),
            (System, system_rows),
            (ScopedControl, control_rows),
            (EvidenceTracking, evidence_rows),
            (SystemEvidenceCapability, capability_rows),
            (Assignment, assignment_rows),
            (Comment, comment_rows),
            (CommentHistory, history_rows),
            (EvidenceCollectionTask, task_rows),
            (Notification, notification_rows),
        ):
            exported_user_ids |= collect_referenced_user_ids(model, rows)

        user_rows = await fetch_rows_in(db, UserModel, UserModel.id, sorted(exported_user_ids))

        organizations = [serialize_row(row) for row in org_rows]
        users = [serialize_row(row) for row in user_rows]
        organization_members = [serialize_row(row) for row in member_rows]
        systems = [serialize_row(row) for row in system_rows]
        scoped_controls = [serialize_row(row) for row in control_rows]
        evidence_tracking = [serialize_row(row) for row in evidence_rows]
        system_evidence_capabilities = [serialize_row(row) for row in capability_rows]
        assignments = [serialize_row(row) for row in assignment_rows]
        comments = [serialize_row(row) for row in comment_rows]
        comment_history = [serialize_row(row) for row in history_rows]
        evidence_collection_tasks = [serialize_row(row) for row in task_rows]
        notifications = [serialize_row(row) for row in notification_rows]

        # Build backup structure with tenant scope metadata
        backup = {
            "metadata": {
                "version": "1.1",
                "created_at": datetime.utcnow().isoformat(),
                "created_by": current_user.email or current_user.user_id,
                "note": "This backup contains USER DATA only, scoped to accessible organisations. Catalog tables (scf_catalog_*) are NOT included.",
                "accessible_organizations": [str(org_id) for org_id in accessible_org_ids],
                "table_counts": {
                    "organizations": len(organizations),
                    "users": len(users),
                    "organization_members": len(organization_members),
                    "systems": len(systems),
                    "scoped_controls": len(scoped_controls),
                    "evidence_tracking": len(evidence_tracking),
                    "system_evidence_capabilities": len(system_evidence_capabilities),
                    "assignments": len(assignments),
                    "comments": len(comments),
                    "comment_history": len(comment_history),
                    "evidence_collection_tasks": len(evidence_collection_tasks),
                    "notifications": len(notifications),
                },
                "export_scope": {
                    "kind": "partial-tenant-export",
                    "note": (
                        "PARTIAL tenant export for org-to-org migration, NOT a "
                        "disaster-recovery backup. It carries "
                        f"{len(TENANT_EXPORT_TABLES)} tables; "
                        f"{len(TENANT_SCOPED_EXCLUDED_TABLES)} other "
                        "organisation-scoped tables are intentionally excluded "
                        "(see excluded_org_scoped_tables). For a complete backup "
                        "use scripts/backup.sh."
                    ),
                    "included_tables": list(TENANT_EXPORT_TABLES),
                    "excluded_org_scoped_tables": TENANT_SCOPED_EXCLUDED_TABLES,
                },
            },
            "data": {
                "organizations": organizations,
                "users": users,
                "organization_members": organization_members,
                "systems": systems,
                "scoped_controls": scoped_controls,
                "evidence_tracking": evidence_tracking,
                "system_evidence_capabilities": system_evidence_capabilities,
                "assignments": assignments,
                "comments": comments,
                "comment_history": comment_history,
                "evidence_collection_tasks": evidence_collection_tasks,
                "notifications": notifications,
            }
        }

        # Invariant: the serialised data set must equal the declared export set.
        # Adding a table to the export means adding it to TENANT_EXPORT_TABLES
        # too — which the honesty test then cross-checks against the org-scoped
        # models. This guards the two from drifting apart.
        if tuple(backup["data"].keys()) != TENANT_EXPORT_TABLES:
            raise RuntimeError(
                "export data keys drifted from TENANT_EXPORT_TABLES: "
                f"{tuple(backup['data'].keys())!r} != {TENANT_EXPORT_TABLES!r}"
            )

        total_records = sum(backup["metadata"]["table_counts"].values())
        logger.info(f"Database backup completed: {total_records} total records across {len(backup['data'])} tables for {len(accessible_org_ids)} organisation(s)")

        return backup

    except HTTPException:
        # The 409 raised for an empty scope is a deliberate answer, not a
        # crash. Without this the handler below would relabel it 500 and the
        # operator would read a precise refusal as a server fault.
        raise
    except Exception as e:
        logger.error(f"Database backup failed: {type(e).__name__}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Database backup failed: {str(e)}"
        )


@router.post("/database/restore")
@rate_limit_auth
async def restore_database(
    request: Request,
    response: Response,
    restore_request: DatabaseRestoreRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_platform_admin)
):
    """
    Restore database from a backup JSON file.

    PLATFORM ADMIN ONLY: This endpoint requires platform administrator privileges.

    This operation will:
    1. Validate the backup format and version
    2. Resolve the organisations the backup targets and check the caller may
       access every one of them
    3. Upsert all records in dependency order
    4. Delete in-scope records the backup does not contain
    5. Return a summary of restored records

    Scope. The restore only ever touches the organisations named in the payload,
    intersected with the caller's accessible organisations. It is not a
    whole-database replace: the previous implementation issued unfiltered
    DELETE statements, so a single-tenant backup wiped every tenant in the
    installation and the request body chose which.

    Strategy. Upsert first, then delete what the backup does not carry, in one
    transaction. Delete-then-insert cannot work here: deleting a scoped_control
    cascades into cdm_mappings, cdm_control_proposals and
    engagement_control_scope, all of which hold human-reviewed work product that
    a backup does not contain. Upserting first means restoring a backup whose id
    set matches the database performs zero deletes and destroys nothing.

    Users and organisations are never deleted. Users are cross-organisation
    identity rather than tenant data, and an organisation delete cascades across
    roughly thirty tables.
    """
    logger.info(f"Database restore initiated by: {current_user.email or current_user.user_id}")

    backup_data = restore_request.backup_data

    # Validate backup structure
    if "metadata" not in backup_data or "data" not in backup_data:
        raise HTTPException(
            status_code=400,
            detail="Invalid backup format: missing 'metadata' or 'data' sections"
        )

    metadata = backup_data["metadata"]
    data = backup_data["data"]

    if not isinstance(metadata, dict) or not isinstance(data, dict):
        raise HTTPException(
            status_code=400,
            detail="Invalid backup format: 'metadata' and 'data' must both be objects"
        )

    # Validate version (support both 1.0 and 1.1)
    version = metadata.get("version")
    if version not in ("1.0", "1.1"):
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported backup version: {version}. Expected: 1.0 or 1.1"
        )

    # ── Resolve the target organisations, then authorise them ──────────────
    # The payload decides the scope, so the payload has to be checked against
    # the caller's own access before anything else happens.
    target_org_ids: List[UUID] = []
    seen_org_ids: Set[UUID] = set()
    raw_org_ids = [row.get("id") for row in backup_table_rows(data, "organizations")]
    if not raw_org_ids:
        raw_org_ids = metadata.get("accessible_organizations") or []
        if not isinstance(raw_org_ids, list):
            raise HTTPException(
                status_code=400,
                detail="Invalid backup: metadata.accessible_organizations must be a list",
            )
    for raw_org_id in raw_org_ids:
        try:
            org_id = UUID(raw_org_id) if isinstance(raw_org_id, str) else raw_org_id
        except (ValueError, AttributeError, TypeError) as exc:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid backup: unparseable organisation id {raw_org_id!r}: {exc}",
            )
        if not isinstance(org_id, UUID):
            raise HTTPException(
                status_code=400,
                detail=f"Invalid backup: unparseable organisation id {raw_org_id!r}",
            )
        if org_id not in seen_org_ids:
            seen_org_ids.add(org_id)
            target_org_ids.append(org_id)

    if not target_org_ids:
        raise HTTPException(
            status_code=400,
            detail=(
                "Invalid backup: no organisations named in data.organizations or "
                "metadata.accessible_organizations, so there is nothing to restore into"
            ),
        )

    accessible_org_ids = set(await admin_scope_org_ids(current_user, db))
    forbidden_org_ids = [org_id for org_id in target_org_ids if org_id not in accessible_org_ids]
    if forbidden_org_ids:
        logger.warning(
            "Restore denied for %s: backup names inaccessible organisation(s) %s",
            current_user.email or current_user.user_id,
            ", ".join(str(org_id) for org_id in forbidden_org_ids),
        )
        raise HTTPException(
            status_code=403,
            detail=(
                "Restore denied: the backup contains organisation(s) you cannot access: "
                + ", ".join(str(org_id) for org_id in forbidden_org_ids)
            ),
        )

    logger.info(
        "Restore scoped to %d organisation(s): %s",
        len(target_org_ids), ", ".join(str(org_id) for org_id in target_org_ids),
    )

    try:
        # ── Materialise every in-scope id set before anything mutates ──────
        # These snapshots decide what the delete sweep may touch, so they have
        # to be taken from the pre-restore database.
        db_member_ids = await fetch_scalars_in(
            db, OrganizationMember.id, OrganizationMember.organization_id, target_org_ids
        )
        db_system_ids = await fetch_scalars_in(
            db, System.id, System.organization_id, target_org_ids
        )
        db_control_ids = await fetch_scalars_in(
            db, ScopedControl.id, ScopedControl.organization_id, target_org_ids
        )
        db_evidence_ids = await fetch_scalars_in(
            db, EvidenceTracking.id, EvidenceTracking.organization_id, target_org_ids
        )
        db_capability_ids = await fetch_scalars_in(
            db, SystemEvidenceCapability.id, SystemEvidenceCapability.system_id, db_system_ids
        )
        db_task_ids = await fetch_scalars_in(
            db, EvidenceCollectionTask.id,
            EvidenceCollectionTask.evidence_tracking_id, db_evidence_ids
        )
        # Assignments and comments are polymorphic over controls, evidence and
        # tasks, so the task ids belong in this union on both sides.
        db_assignable_ids = db_control_ids + db_evidence_ids + db_task_ids
        db_assignment_ids = await fetch_scalars_in(
            db, Assignment.id, Assignment.assignable_id, db_assignable_ids
        )
        db_comment_ids = await fetch_scalars_in(
            db, Comment.id, Comment.commentable_id, db_assignable_ids
        )
        db_comment_history_ids = await fetch_scalars_in(
            db, CommentHistory.id, CommentHistory.comment_id, db_comment_ids
        )
        # Notifications are scoped by the entity referenced, never by user_id:
        # a user who belongs to two tenants shares one row set, and scoping by
        # user_id would delete the other tenant's notifications.
        db_notification_ids = await fetch_scalars_in(
            db, Notification.id, Notification.reference_id, db_assignable_ids + db_comment_ids
        )

        in_scope_ids: Dict[str, List[Any]] = {
            "organization_members": db_member_ids,
            "systems": db_system_ids,
            "scoped_controls": db_control_ids,
            "evidence_tracking": db_evidence_ids,
            "system_evidence_capabilities": db_capability_ids,
            "evidence_collection_tasks": db_task_ids,
            "assignments": db_assignment_ids,
            "comments": db_comment_ids,
            "comment_history": db_comment_history_ids,
            "notifications": db_notification_ids,
        }

        delete_models = {
            "organization_members": OrganizationMember,
            "systems": System,
            "scoped_controls": ScopedControl,
            "evidence_tracking": EvidenceTracking,
            "system_evidence_capabilities": SystemEvidenceCapability,
            "evidence_collection_tasks": EvidenceCollectionTask,
            "assignments": Assignment,
            "comments": Comment,
            "comment_history": CommentHistory,
            "notifications": Notification,
        }

        existing_counts = {table: len(ids) for table, ids in in_scope_ids.items()}
        records_in_backup = {
            table: len(backup_table_rows(data, table))
            for table in (
                "organizations", "users", "organization_members", "systems",
                "scoped_controls", "evidence_tracking", "system_evidence_capabilities",
                "assignments", "comments", "comment_history",
                "evidence_collection_tasks", "notifications",
            )
        }
        would_delete_counts = {
            table: len(set(ids) - backup_row_ids(data, table))
            for table, ids in in_scope_ids.items()
        }

        # ── Preview: report, mutate nothing ────────────────────────────────
        if not restore_request.confirm_clear:
            # Only reads have run; roll the transaction back explicitly so the
            # preview cannot leave anything behind.
            await db.rollback()
            return {
                "status": "preview",
                "message": "This is a preview. Set confirm_clear=true to proceed with restore.",
                "backup_metadata": metadata,
                "records_to_restore": metadata.get("table_counts", {}),
                "target_organizations": [str(org_id) for org_id in target_org_ids],
                "records_in_backup": records_in_backup,
                "existing_counts": existing_counts,
                "would_delete_counts": would_delete_counts,
            }

        # ── Bound the mutating transaction ─────────────────────────────────
        # The engine sets neither timeout, so without these one restore can
        # hold locks indefinitely. set_config(..., is_local => true) is exactly
        # SET LOCAL: it applies to the transaction the reads above already
        # opened and expires with it. Used in preference to SET LOCAL because
        # SET does not accept bind parameters and would force the value to be
        # interpolated into the statement; set_config takes it as a parameter.
        await db.execute(
            text("SELECT set_config('statement_timeout', :timeout, true)"),
            {"timeout": str(int(RESTORE_STATEMENT_TIMEOUT_MS))},
        )
        await db.execute(
            text("SELECT set_config('lock_timeout', :timeout, true)"),
            {"timeout": str(int(RESTORE_LOCK_TIMEOUT_MS))},
        )

        # ── Cross-tenant write guard (#870) ────────────────────────────────
        # The authorisation gate above proved the caller may touch
        # target_org_ids, but it validated only data.organizations — the
        # individual child rows still carry their own organization_id and
        # parent references. A hand-edited backup can name an in-scope org in
        # data.organizations to pass the gate while smuggling child rows keyed
        # to another tenant's ids, overwriting them by primary key. Every
        # upserted row is therefore required to resolve to an org in
        # target_org_ids: directly for the org-bearing tables, or through a
        # parent already in scope for the polymorphic ones. "In scope" for a
        # parent is a pre-existing row snapshotted above OR a row this restore
        # has just accepted, so the topology mirrors the delete snapshot
        # exactly — a row is writable iff it would also be deletable, and the
        # endpoint can only ever touch the caller's own organisations.
        target_org_set = set(target_org_ids)

        def _direct_ids(table: str, org_key: str = "organization_id") -> Set[UUID]:
            kept: Set[UUID] = set()
            for row in backup_table_rows(data, table):
                if coerce_uuid(row.get(org_key)) not in target_org_set:
                    continue
                row_id = coerce_uuid(row.get("id"))
                if row_id is not None:
                    kept.add(row_id)
            return kept

        def _indirect_ids(table: str, fk_key: str, parent_scope: Set[UUID]) -> Set[UUID]:
            kept: Set[UUID] = set()
            for row in backup_table_rows(data, table):
                if coerce_uuid(row.get(fk_key)) not in parent_scope:
                    continue
                row_id = coerce_uuid(row.get("id"))
                if row_id is not None:
                    kept.add(row_id)
            return kept

        allowed_ids: Dict[str, Set[UUID]] = {}
        # organizations resolve to themselves; already authorised above, so this
        # is a defence-in-depth no-op, but keeps every table under one rule.
        allowed_ids["organizations"] = {
            oid for row in backup_table_rows(data, "organizations")
            if (oid := coerce_uuid(row.get("id"))) in target_org_set
        }
        # Directly org-scoped tables.
        allowed_ids["organization_members"] = _direct_ids("organization_members")
        allowed_ids["systems"] = _direct_ids("systems")
        allowed_ids["scoped_controls"] = _direct_ids("scoped_controls")
        allowed_ids["evidence_tracking"] = _direct_ids("evidence_tracking")
        # evidence_collection_tasks carries a denormalised NOT NULL
        # organization_id (models.py) whose composite FK is validated against
        # evidence_tracking's org, so the direct check is authoritative.
        allowed_ids["evidence_collection_tasks"] = _direct_ids("evidence_collection_tasks")
        # Indirectly scoped tables: the parent must already be in scope, which
        # includes both the pre-restore snapshot and the rows just accepted.
        system_scope = set(db_system_ids) | allowed_ids["systems"]
        allowed_ids["system_evidence_capabilities"] = _indirect_ids(
            "system_evidence_capabilities", "system_id", system_scope
        )
        control_scope = set(db_control_ids) | allowed_ids["scoped_controls"]
        evidence_scope = set(db_evidence_ids) | allowed_ids["evidence_tracking"]
        task_scope = set(db_task_ids) | allowed_ids["evidence_collection_tasks"]
        assignable_scope = control_scope | evidence_scope | task_scope
        allowed_ids["assignments"] = _indirect_ids(
            "assignments", "assignable_id", assignable_scope
        )
        allowed_ids["comments"] = _indirect_ids(
            "comments", "commentable_id", assignable_scope
        )
        comment_scope = set(db_comment_ids) | allowed_ids["comments"]
        allowed_ids["comment_history"] = _indirect_ids(
            "comment_history", "comment_id", comment_scope
        )
        # notifications are handled at their upsert step, after
        # backfill_notification_orgs has resolved organization_id on pre-#852
        # rows — validating raw rows here would drop legitimate old backups.

        def scope_for(table: str) -> Optional[Callable[[Dict[str, Any]], bool]]:
            ids = allowed_ids.get(table)
            if ids is None:
                return None
            return lambda values: values.get("id") in ids

        upserted_counts: Dict[str, int] = {}
        deleted_counts: Dict[str, int] = {}
        nulled_references: Dict[str, int] = {}
        skipped_rows: Dict[str, int] = {}

        def record(table: str, result: Tuple[int, int, int]) -> None:
            upserted, nulled, dropped = result
            upserted_counts[table] = upserted
            if nulled:
                nulled_references[table] = nulled_references.get(table, 0) + nulled
            if dropped:
                skipped_rows[table] = dropped

        # Every write below is a Core statement, dispatched as it is executed,
        # so there is no pending ORM state and nothing for autoflush to miss.
        # Parents are visible to the child reference checks immediately.

        # ── Upsert, parents before children ────────────────────────────────
        # 1. Organizations. Never deleted, and written through an explicit
        # column list so a column added later is carried without code changes.
        record("organizations", await restore_table(
            db, Organization, backup_table_rows(data, "organizations"),
            scope_predicate=scope_for("organizations"),
        ))

        # 2. Users: insert-if-absent only, never updated. The payload does not
        # carry is_platform_admin or oidc_issuer, so updating an existing user
        # would blank the issuer that auth.py matches on and clear the platform
        # admin flag — locking every administrator out with the same request
        # that restored their data. is_platform_admin is forced False rather
        # than read from the payload so a hand-edited backup cannot grant it.
        record("users", await restore_table(
            db, UserModel, backup_table_rows(data, "users"),
            exclude=USER_PROTECTED_COLUMNS,
            overrides={"is_platform_admin": False},
            insert_only=True,
        ))

        # 3. Organization members
        record("organization_members", await restore_table(
            db, OrganizationMember, backup_table_rows(data, "organization_members"),
            scope_predicate=scope_for("organization_members"),
        ))

        # 4. Systems (v1.1+ backups only)
        record("systems", await restore_table(
            db, System, backup_table_rows(data, "systems"),
            scope_predicate=scope_for("systems"),
        ))

        # 5. Scoped controls. Backups written before the CCF→SCF rename carry
        # ccf_id, so it is folded into scf_id before hydration.
        scoped_control_rows = []
        for row in backup_table_rows(data, "scoped_controls"):
            if not row.get("scf_id") and row.get("ccf_id"):
                row = {**row, "scf_id": row["ccf_id"]}
            scoped_control_rows.append(row)
        record("scoped_controls", await restore_table(
            db, ScopedControl, scoped_control_rows,
            scope_predicate=scope_for("scoped_controls"),
        ))

        # 6. Evidence tracking
        record("evidence_tracking", await restore_table(
            db, EvidenceTracking, backup_table_rows(data, "evidence_tracking"),
            scope_predicate=scope_for("evidence_tracking"),
        ))

        # 7. System evidence capabilities (v1.1+ backups only)
        record("system_evidence_capabilities", await restore_table(
            db, SystemEvidenceCapability,
            backup_table_rows(data, "system_evidence_capabilities"),
            scope_predicate=scope_for("system_evidence_capabilities"),
        ))

        # 8. Assignments
        record("assignments", await restore_table(
            db, Assignment, backup_table_rows(data, "assignments"),
            scope_predicate=scope_for("assignments"),
        ))

        # 9. Comments, first pass. parent_comment_id is self-referential, so it
        # is held back until every comment in the payload exists.
        comment_rows = backup_table_rows(data, "comments")
        record("comments", await restore_table(
            db, Comment, comment_rows, exclude=frozenset({"parent_comment_id"}),
            scope_predicate=scope_for("comments"),
        ))

        # Comments, second pass. Written for every row, not only the threaded
        # ones, so a comment un-threaded since the backup is un-threaded here
        # too. A parent that no longer resolves is nulled rather than failing
        # the restore on a foreign key violation.
        requested_parent_ids: Set[UUID] = set()
        for row in comment_rows:
            raw_parent_id = row.get("parent_comment_id")
            if raw_parent_id is not None:
                requested_parent_ids.add(
                    UUID(raw_parent_id) if isinstance(raw_parent_id, str) else raw_parent_id
                )
        resolvable_parent_ids = await fetch_existing_ids(
            db, "comments", "id", requested_parent_ids
        )
        parent_updates = []
        unresolvable_parents = 0
        for row in comment_rows:
            raw_parent_id = row.get("parent_comment_id")
            parent_id = None
            if raw_parent_id is not None:
                candidate = UUID(raw_parent_id) if isinstance(raw_parent_id, str) else raw_parent_id
                if candidate in resolvable_parent_ids:
                    parent_id = candidate
                else:
                    unresolvable_parents += 1
            # Same class of defect as the old `row["due_date"]`: backup_table_rows
            # validates that a row is an object, never that it carries an id, so
            # direct indexing raises mid-restore on a hand-edited file. An id-less
            # row cannot have been upserted either (the upsert keys on id), so
            # there is nothing to point a parent at.
            raw_comment_id = row.get("id")
            if raw_comment_id is None:
                continue
            comment_id = UUID(raw_comment_id) if isinstance(raw_comment_id, str) else raw_comment_id
            # Only rows the first pass actually wrote may be updated here. The
            # cross-tenant guard (#870) drops out-of-scope comments before the
            # upsert, so a parent_update naming one would match zero rows — and
            # SQLAlchemy's bulk ORM update raises StaleDataError on a 0-row
            # mapping rather than ignoring it. Skipping non-upserted ids keeps
            # the bulk update's one-row-per-mapping contract.
            if comment_id not in allowed_ids["comments"]:
                continue
            parent_updates.append({
                "id": comment_id,
                "parent_comment_id": parent_id,
            })
        if parent_updates:
            # Bulk update by primary key: each mapping names the row's own id
            # plus the column to set.
            for chunk in chunked(parent_updates, UPSERT_CHUNK_SIZE):
                await db.execute(update(Comment), chunk)
        if unresolvable_parents:
            logger.warning(
                "Restore of comments: nulled %d parent_comment_id value(s) that do not resolve",
                unresolvable_parents,
            )
            nulled_references["comments"] = (
                nulled_references.get("comments", 0) + unresolvable_parents
            )

        # 10. Evidence collection tasks
        record("evidence_collection_tasks", await restore_table(
            db, EvidenceCollectionTask, backup_table_rows(data, "evidence_collection_tasks"),
            scope_predicate=scope_for("evidence_collection_tasks"),
        ))

        # 11. Notifications. The scope set is built from the backfilled rows, not
        # the raw payload: backfill_notification_orgs derives organization_id on
        # pre-#852 rows from the referenced entity this restore has already
        # written, so validating the raw rows would drop legitimate old backups.
        # A row whose reference resolves to a foreign tenant is given that
        # tenant's org by the backfill and then dropped here.
        notification_rows = await backfill_notification_orgs(
            db, backup_table_rows(data, "notifications")
        )
        allowed_ids["notifications"] = {
            nid for row in notification_rows
            if coerce_uuid(row.get("organization_id")) in target_org_set
            and (nid := coerce_uuid(row.get("id"))) is not None
        }
        record("notifications", await restore_table(
            db, Notification, notification_rows,
            scope_predicate=scope_for("notifications"),
        ))

        # 12. Comment history
        record("comment_history", await restore_table(
            db, CommentHistory, backup_table_rows(data, "comment_history"),
            scope_predicate=scope_for("comment_history"),
        ))

        # ── Delete in-scope rows the backup does not contain ───────────────
        # Children before parents, and only ids that were already in scope
        # before the upserts ran. Restoring a backup whose id set matches the
        # database deletes nothing at all.
        for table in RESTORE_DELETE_ORDER:
            absent_ids = set(in_scope_ids[table]) - backup_row_ids(data, table)
            deleted_counts[table] = await delete_rows_by_id(
                db, delete_models[table], absent_ids
            )

        # One commit, for the upserts and the deletes together.
        await db.commit()

        total_upserted = sum(upserted_counts.values())
        total_deleted = sum(deleted_counts.values())
        logger.info(
            "Database restore completed for %d organisation(s): %d record(s) written, "
            "%d record(s) removed",
            len(target_org_ids), total_upserted, total_deleted,
        )

        return {
            "status": "success",
            "message": (
                f"Database restored successfully. {total_upserted} records written, "
                f"{total_deleted} removed across {len(target_org_ids)} organisation(s)."
            ),
            "restored_by": current_user.email or current_user.user_id,
            "restored_at": datetime.utcnow().isoformat(),
            "original_backup_created_at": metadata.get("created_at"),
            "original_backup_created_by": metadata.get("created_by"),
            "target_organizations": [str(org_id) for org_id in target_org_ids],
            # Counted from the row counts the database reported, not from the
            # length of the payload.
            "upserted_counts": upserted_counts,
            "deleted_counts": deleted_counts,
            # Retained under its original name for existing callers.
            "restored_counts": upserted_counts,
            "nulled_references": nulled_references,
            "skipped_rows": skipped_rows,
        }

    except HTTPException:
        # A malformed payload is the caller's error; keep its status code
        # rather than reporting it as a server failure.
        await db.rollback()
        raise
    except Exception as e:
        await db.rollback()
        logger.error(f"Database restore failed: {type(e).__name__}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Database restore failed: {str(e)}"
        )


async def get_catalog_counts(db: AsyncSession) -> Dict[str, int]:
    """
    Get counts of catalog items from the database.

    Queries the seeded catalog tables instead of reading from files.
    """
    try:
        controls_count = await db.scalar(
            select(func.count()).select_from(SCFCatalogControl)
        )
        evidence_count = await db.scalar(
            select(func.count()).select_from(SCFCatalogEvidence)
        )

        return {
            "collection_interfaces": 0,  # Legacy CCF concept, not in SCF
            "evidence_items": evidence_count or 0,
            "controls": controls_count or 0
        }
    except Exception as e:
        logger.warning(f"Failed to get catalog counts from database: {e}")
        return {
            "collection_interfaces": 0,
            "evidence_items": 0,
            "controls": 0
        }


def get_git_info(repo_path: str) -> Optional[Dict[str, str]]:
    """
    Get git commit hash and tag info from a repository path.
    """
    try:
        # Get current commit hash (short)
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=5
        )
        commit = result.stdout.strip() if result.returncode == 0 else None

        # Try to get tag
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=5
        )
        tag = result.stdout.strip() if result.returncode == 0 else None

        return {"commit": commit, "tag": tag}
    except Exception as e:
        logger.warning(f"Failed to get git info from {repo_path}: {e}")
        return None


def get_platform_version() -> str:
    """
    Get platform version from package.json (mounted at /version/package.json).
    Falls back to PLATFORM_VERSION env var if file not available.
    """
    package_json_path = Path("/version/package.json")
    if package_json_path.exists():
        try:
            with open(package_json_path) as f:
                data = json.load(f)
                version = data.get("version")
                if version:
                    logger.debug(f"Platform version from package.json: {version}")
                    return version
        except Exception as e:
            logger.warning(f"Failed to read package.json: {e}")

    # Fallback to environment variable
    return os.getenv("PLATFORM_VERSION", "0.0.0")


def get_catalog_version() -> str:
    """
    Get catalog version from git describe (catalog repo mounted at /version/catalog).
    Falls back to CATALOG_VERSION env var if git not available.
    """
    catalog_repo_path = "/version/catalog"

    # Try git describe first
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            cwd=catalog_repo_path,
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0 and result.stdout.strip():
            version = result.stdout.strip()
            logger.debug(f"Catalog version from git: {version}")
            return version
    except Exception as e:
        logger.warning(f"Failed to get catalog version from git: {e}")

    # Fallback to environment variable
    return os.getenv("CATALOG_VERSION", "unknown")


def get_build_info() -> Optional[Dict[str, Any]]:
    """
    Read the image-baked build metadata (Dockerfile.backend writes this at build
    time). Canonical path is the container root /build_info.json (outside the
    ./backend:/app bind mount so it is never shadowed); /app/build_info.json is a
    silent fallback for image-only deployments. Returns None when absent (dev image).
    """
    for candidate in ("/build_info.json", "/app/build_info.json"):
        build_info_path = Path(candidate)
        if not build_info_path.exists():
            continue
        try:
            with open(build_info_path) as f:
                data = json.load(f)
            if isinstance(data, dict):
                return data
        except Exception as e:
            logger.warning(f"Failed to read build_info at {candidate}: {e}")
    return None


def _update_check_enabled() -> bool:
    """Update check is ON unless SCF_UPDATE_CHECK is explicitly 'false'/'0'."""
    return os.getenv("SCF_UPDATE_CHECK", "").strip().lower() not in ("false", "0")


async def _build_update_object(installed_version: str) -> Dict[str, Any]:
    """
    Build the admin-only ``update`` object from the Redis key the poller writes
    (upgrade design Part C). Redis being unreachable must degrade to an unknown
    state, never error the endpoint.
    """
    if not _update_check_enabled():
        return {"check_enabled": False}

    unknown = {"check_enabled": True, "update_available": None, "last_checked": None}
    try:
        redis_client = await get_redis_client()
        raw = await redis_client.get("scf:update:latest")
    except Exception as e:
        logger.warning(f"Update state Redis read failed (degrading to unknown): {e}")
        return unknown

    if not raw:
        return unknown
    try:
        state = json.loads(raw)
    except (ValueError, TypeError):
        return unknown

    if state.get("check_enabled") is False:
        return {"check_enabled": False}

    status = state.get("status")
    if status == "manifest_missing":
        return {
            "check_enabled": True,
            "update_available": None,
            "status": "manifest_missing",
            "last_checked": state.get("checked_at"),
        }
    if status == "ok":
        latest = state.get("latest_version")
        min_upgradable = state.get("min_upgradable_version")
        update_available = bool(latest and compare_versions(latest, installed_version) > 0)
        skip_blocked = bool(min_upgradable and compare_versions(installed_version, min_upgradable) < 0)
        return {
            "check_enabled": True,
            "installed_version": installed_version,
            "latest_version": latest,
            "update_available": update_available,
            "breaking": bool(state.get("breaking", False)),
            "release_url": state.get("release_url"),
            "summary": state.get("summary"),
            "min_upgradable_version": min_upgradable,
            "skip_blocked": skip_blocked,
            "last_checked": state.get("checked_at"),
        }

    # Unrecognised cached status → treat as unknown.
    return {"check_enabled": True, "update_available": None, "last_checked": state.get("checked_at")}


@router.get("/version")
# @limiter.limit(READ_RATE_LIMIT)  # Temporarily disabled
async def get_version_info(
    request: Request,
    db: AsyncSession = Depends(get_db),
    user: Optional[User] = Depends(optional_auth),
):
    """
    Get version information for the platform and catalog.

    Response is tiered (upgrade design §8.6, red-team M3):
    - Anonymous / unauthenticated callers get only a coarse liveness signal —
      the cosmetic API contract version, no precise release version, git commit,
      catalog counts, or update object. Broadcasting a precise, matchable
      version to anonymous callers of a compliance product turns a single
      request into an exploitability beacon, so this tier stays deliberately blind.
    - Any authenticated user gets the full platform/catalog detail plus the
      ``update`` object (from the update poller's Redis cache) and the image
      ``build`` stamp. Update visibility is a feature — it nudges everyone to
      get a stale/vulnerable deployment patched — and the caller is already
      inside the tenant, so the fingerprinting concern does not apply.
    """
    logger.info("Version info requested")

    # Gate on authentication, not platform-admin: the sensitive boundary is
    # authenticated-vs-anonymous (M3 fingerprinting), not admin-vs-member.
    if user is None:
        return {"platform": {"api_version": "1.0.0"}, "status": "ok"}

    # Read versions dynamically from actual sources. The catalog version
    # authority is the import-run ledger (plan §4.2.5); the git-describe path
    # is consulted only while no upgrade run has ever been applied.
    from services.catalog_apply import get_current_catalog_version

    platform_version = get_platform_version()
    catalog_version = await get_current_catalog_version(db) or get_catalog_version()

    # Get catalog counts from database
    catalog_counts = await get_catalog_counts(db)

    # Try to get git info for backend (if running in dev with git)
    git_info = get_git_info("/app")

    build_info = get_build_info()

    return {
        "platform": {
            "version": platform_version,
            "api_version": "1.0.0",
            "git_commit": git_info.get("commit") if git_info else None
        },
        "catalog": {
            "version": catalog_version,
            "controls_count": catalog_counts["controls"],
            "evidence_count": catalog_counts["evidence_items"],
            "interface_count": catalog_counts["collection_interfaces"]
        },
        "update": await _build_update_object(platform_version),
        "build": {"build_stamp": build_info.get("build_stamp")} if build_info else None,
    }


@router.get("/database/catalog-stats")
# @limiter.limit(READ_RATE_LIMIT)  # Temporarily disabled
async def get_catalog_stats(
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_auth)
):
    """
    Get statistics for SCF catalog tables (reference data).

    Requires authentication.

    Catalog tables are seeded from SCF JSON files on application startup and contain:
    - scf_catalog_controls: SCF control definitions with full metadata
    - scf_catalog_domains: SCF domain definitions
    - scf_catalog_evidence: Evidence Request List (ERL) entries
    - scf_catalog_assessment_objectives: Assessment objectives for controls

    NOTE: Catalog data is READ-ONLY reference data and is NOT included in backups.
    """
    logger.info(f"Catalog stats accessed by: {current_user.email or current_user.user_id}")

    try:
        # Count catalog tables
        controls_count = await db.scalar(
            select(func.count()).select_from(SCFCatalogControl)
        )
        domains_count = await db.scalar(
            select(func.count()).select_from(SCFCatalogDomain)
        )
        evidence_count = await db.scalar(
            select(func.count()).select_from(SCFCatalogEvidence)
        )
        ao_count = await db.scalar(
            select(func.count()).select_from(SCFCatalogAssessmentObjective)
        )

        # Catalog version authority is the import-run ledger (plan §4.2.5);
        # row-sampling remains only as the pre-first-upgrade fallback.
        from services.catalog_apply import get_current_catalog_version

        catalog_version = await get_current_catalog_version(db)
        if catalog_version is None:
            version_result = await db.execute(
                select(SCFCatalogControl.catalog_version).limit(1)
            )
            catalog_version = version_result.scalar() or "unknown"

        return {
            "status": "healthy",
            "catalog_version": catalog_version,
            "tables": {
                "scf_catalog_controls": controls_count or 0,
                "scf_catalog_domains": domains_count or 0,
                "scf_catalog_evidence": evidence_count or 0,
                "scf_catalog_assessment_objectives": ao_count or 0
            },
            "total_records": (
                (controls_count or 0) +
                (domains_count or 0) +
                (evidence_count or 0) +
                (ao_count or 0)
            ),
            "note": "Catalog data is READ-ONLY reference data seeded from SCF JSON files. Not included in backups."
        }
    except HTTPException:
        # A status this endpoint chose deliberately; re-raise it unchanged
        # rather than relabelling it 500 below.
        raise
    except Exception as e:
        logger.error(f"Failed to retrieve catalog statistics: {type(e).__name__}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to retrieve catalog statistics: {str(e)}"
        )
