"""Everything that touches the filesystem.

Ordering matters and is part of the contract:

1. the sentinel, created ``O_CREAT|O_EXCL|O_NOFOLLOW`` so a second launch, a
   dangling symlink and a race all lose in the same way;
2. the ten secret files, ``0600``, never overwriting an existing file;
3. ``/out/.env``, ``0600``, non-secret keys only;
4. the provisioning token, deleted.
"""

from __future__ import annotations

import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from . import get_logger
from .generate import SECRET_FILE_NAMES

logger = get_logger()

SENTINEL_NAME = ".provisioned"
TOKEN_NAME = ".provision-token"
SENTINEL_VERSION = 1

SECRET_FILE_MODE = 0o600
SECRETS_DIR_MODE = 0o700
ENV_FILE_MODE = 0o600

# .env.example's bundled-Keycloak defaults, reproduced verbatim (non-secret only).
KEYCLOAK_TEMPLATE_DEFAULTS: dict[str, str] = {
    "OIDC_ISSUER": "http://localhost:8081/realms/scf",
    "OIDC_DISCOVERY_URL": "http://keycloak:8080/realms/scf",
    "OIDC_CLIENT_ID": "scf-platform",
    "OIDC_REDIRECT_URI": "http://localhost:5173/api/auth/callback",
}
DEFAULT_REDIRECT_URI = KEYCLOAK_TEMPLATE_DEFAULTS["OIDC_REDIRECT_URI"]

ENV_HEADER = (
    "# Generated by scripts/install.sh on {when}.\n"
    "# Secrets live in SCF_SECRETS_DIR, not here.\n"
    "# Copy any further non-secret option you need from .env.example.\n"
)


def is_placeholder(value: str | None) -> bool:
    """Mirror of services/secrets.is_placeholder.

    Deliberately duplicated: the installer runs before the app exists and must
    not import backend code.  Keep the two in step.
    """
    if value is None:
        return True
    text = value.strip()
    if not text:
        return True
    lowered = text.lower()
    return lowered.startswith("changeme") or lowered == "minioadmin" or text.startswith("CHANGE_ME")


class AlreadyProvisioned(Exception):
    """The sentinel exists (or its path is a symlink): refuse, never overwrite."""


def ensure_secrets_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    try:
        # SECRETS_DIR_MODE is 0o700 (owner only); the rule cannot resolve the constant.
        # nosemgrep: python.lang.security.audit.insecure-file-permissions.insecure-file-permissions
        os.chmod(path, SECRETS_DIR_MODE)
    except PermissionError:  # pragma: no cover - bind mount owned elsewhere
        logger.warning("could not tighten the secrets directory to 0700")
    return path


def sentinel_path(secrets_dir: Path) -> Path:
    return secrets_dir / SENTINEL_NAME


def is_provisioned(secrets_dir: Path) -> bool:
    """True when the sentinel exists as a real file.

    ``os.path.exists`` follows symlinks, so a dangling symlink named
    ``.provisioned`` reads as absent — ``lstat`` does not.
    """
    try:
        os.lstat(sentinel_path(secrets_dir))
    except FileNotFoundError:
        return False
    return True


def create_sentinel(secrets_dir: Path, *, db: str, idp: str) -> Path:
    """First write of a provisioning run.  Atomic, symlink-proof, race-proof."""
    path = sentinel_path(secrets_dir)
    payload = {
        "version": SENTINEL_VERSION,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "db": db,
        "idp": idp,
    }
    try:
        fd = os.open(
            path, os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_WRONLY, SECRET_FILE_MODE
        )
    except FileExistsError as exc:
        raise AlreadyProvisioned("already provisioned") from exc
    except OSError as exc:
        # O_NOFOLLOW on an existing symlink raises ELOOP, not FileExistsError.
        raise AlreadyProvisioned("already provisioned") from exc
    with os.fdopen(fd, "w") as handle:
        handle.write(json.dumps(payload, indent=2) + "\n")
    return path


def write_secret_file(secrets_dir: Path, name: str, value: str) -> bool:
    """Write one 0600 secret file.  Returns False when it already existed.

    An existing file is NEVER overwritten: re-provisioning must not regenerate
    SCF_SECRET_KEY (which would brick every stored tier-3 credential) or
    DB_PASSWORD (which would not match an initialised postgres volume).
    """
    path = secrets_dir / name
    try:
        fd = os.open(
            path, os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_WRONLY, SECRET_FILE_MODE
        )
    except (FileExistsError, OSError):
        logger.info("keeping the existing %s (never overwritten)", name)
        return False
    with os.fdopen(fd, "w") as handle:
        handle.write(value or "")
    os.chmod(path, SECRET_FILE_MODE)
    return True


def write_secret_files(secrets_dir: Path, values: dict[str, str]) -> dict[str, bool]:
    """Write all ten files (unused ones empty) and report which were created."""
    written: dict[str, bool] = {}
    for name in SECRET_FILE_NAMES:
        written[name] = write_secret_file(secrets_dir, name, values.get(name, ""))
    return written


def read_secret_file(secrets_dir: Path, name: str) -> str | None:
    path = secrets_dir / name
    try:
        return path.read_text().strip()
    except (FileNotFoundError, IsADirectoryError, PermissionError):
        return None


def read_provision_token(secrets_dir: Path) -> str | None:
    return read_secret_file(secrets_dir, TOKEN_NAME)


def delete_provision_token(secrets_dir: Path) -> bool:
    try:
        (secrets_dir / TOKEN_NAME).unlink()
        return True
    except FileNotFoundError:
        return False


def build_env(
    *,
    host_secrets_dir: str,
    db: dict[str, Any],
    idp: dict[str, Any],
    when: str | None = None,
) -> str:
    """Render `.env`.  NON-SECRET KEYS ONLY — this is the whole key set."""
    idp_type = idp.get("type", "none")
    lines: list[str] = []
    lines.append(ENV_HEADER.format(when=when or datetime.now(timezone.utc).isoformat()))

    env: list[tuple[str, str]] = [
        ("SCF_SECRETS_DIR", host_secrets_dir),
        ("COMPOSE_FILE", "docker-compose.yml:docker-compose.secrets.yml"),
    ]
    if idp_type == "bundled_keycloak":
        env.append(("COMPOSE_PROFILES", "idp"))
    env += [
        ("ENVIRONMENT", "production"),
        ("OSS_SINGLE_TENANT", "1"),
        ("DB_HOST", str(db.get("host") or "postgres")),
        ("DB_PORT", str(db.get("port") or 5432)),
        ("DB_NAME", str(db.get("dbname") or "cg_scf")),
        ("DB_USER", str(db.get("user") or "cg")),
        # unset or `disable` means "no ssl parameter" to backend/db_url.py
        ("DB_SSLMODE", "" if db.get("type") == "bundled" else str(db.get("sslmode") or "")),
    ]

    if idp_type == "bundled_keycloak":
        env.append(("KC_ADMIN_USER", str(idp.get("kc_admin_user") or "admin")))
        env.append(
            ("BOOTSTRAP_ADMIN_EMAIL", str(idp.get("bootstrap_admin_email") or "").strip().lower())
        )
        for key, value in KEYCLOAK_TEMPLATE_DEFAULTS.items():
            env.append((key, value))
        env.append(("VITE_OIDC_ENABLED", "true"))
    elif idp_type == "external_oidc":
        issuer = str(idp.get("oidc_issuer") or "").strip().rstrip("/")
        env.append(("OIDC_ISSUER", issuer))
        env.append(("OIDC_DISCOVERY_URL", issuer))
        env.append(("OIDC_CLIENT_ID", str(idp.get("oidc_client_id") or "").strip()))
        env.append(("OIDC_REDIRECT_URI", DEFAULT_REDIRECT_URI))
        env.append(("VITE_OIDC_ENABLED", "true"))

    for key, value in env:
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def env_keys(content: str) -> list[str]:
    """Keys actually set by a rendered `.env`, in order."""
    keys: list[str] = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        keys.append(line.split("=", 1)[0])
    return keys


def write_env(out_dir: Path, content: str) -> Path:
    path = out_dir / ".env"
    fd = os.open(path, os.O_CREAT | os.O_TRUNC | os.O_WRONLY | os.O_NOFOLLOW, ENV_FILE_MODE)
    with os.fdopen(fd, "w") as handle:
        handle.write(content)
    os.chmod(path, ENV_FILE_MODE)
    return path


def backup_env(out_dir: Path) -> Path:
    """Copy `.env` aside at 0600 before rewriting it (import-env)."""
    source = out_dir / ".env"
    target = out_dir / f".env.bak.{int(time.time())}"
    fd = os.open(target, os.O_CREAT | os.O_EXCL | os.O_WRONLY, ENV_FILE_MODE)
    with os.fdopen(fd, "w") as handle:
        handle.write(source.read_text())
    os.chmod(target, ENV_FILE_MODE)
    return target


def parse_env(content: str) -> dict[str, str]:
    """Minimal `.env` reader: KEY=VALUE, ignoring comments and blank lines."""
    values: dict[str, str] = {}
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key] = value
    return values


def strip_secret_lines(content: str, names: Iterable[str], extra: dict[str, str]) -> str:
    """Rewrite `.env` without the credential lines, plus the new pointers."""
    drop = set(names)
    kept: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key = stripped.split("=", 1)[0].strip()
            if key in drop or key in extra:
                continue
        kept.append(line)
    body = "\n".join(kept).rstrip("\n")
    added = "\n".join(f"{k}={v}" for k, v in extra.items())
    return f"{body}\n\n# Added by scripts/install.sh --import-env\n{added}\n"
