"""Fingerprint determinism and change attribution."""
import pytest

from services.doc_gen.fingerprint import compute_fingerprint, describe_change, sha256


def control(scf_id, description="desc", status="implemented", objectives=None):
    return {
        "scf_id": scf_id,
        "control_name": f"Name {scf_id}",
        "control_description": description,
        "implementation_status": status,
        "implementation_notes": None,
        "maturity_level": "L3",
        "owner": "Security",
        "assessment_objectives": objectives or [],
    }


def test_sha256_is_stable():
    assert sha256("abc") == sha256("abc")
    assert sha256("abc") != sha256("abd")
    assert len(sha256("abc")) == 64


def test_same_inputs_produce_same_fingerprint():
    controls = [control("IAC-01"), control("GOV-02")]
    a = compute_fingerprint(controls, "sys", "user")
    b = compute_fingerprint(controls, "sys", "user")
    assert a.input_fingerprint == b.input_fingerprint


def test_control_order_does_not_affect_fingerprint():
    forward = [control("AAA-01"), control("BBB-02"), control("CCC-03")]
    reverse = list(reversed(forward))
    assert (
        compute_fingerprint(forward, "sys", "user").input_fingerprint
        == compute_fingerprint(reverse, "sys", "user").input_fingerprint
    )


def test_objective_order_does_not_affect_fingerprint():
    objs = [
        {"ao_id": "AAA-01.2", "objective_text": "second"},
        {"ao_id": "AAA-01.1", "objective_text": "first"},
    ]
    a = compute_fingerprint([control("AAA-01", objectives=objs)], "s", "u")
    b = compute_fingerprint([control("AAA-01", objectives=list(reversed(objs)))], "s", "u")
    assert a.input_fingerprint == b.input_fingerprint


def test_changed_control_description_changes_fingerprint():
    a = compute_fingerprint([control("AAA-01", description="one")], "s", "u")
    b = compute_fingerprint([control("AAA-01", description="two")], "s", "u")
    assert a.input_fingerprint != b.input_fingerprint
    assert a.input_components.controls_hash != b.input_components.controls_hash


def test_changed_template_changes_only_template_hash():
    controls = [control("AAA-01")]
    a = compute_fingerprint(controls, "sys one", "user")
    b = compute_fingerprint(controls, "sys two", "user")
    assert a.input_fingerprint != b.input_fingerprint
    assert a.input_components.controls_hash == b.input_components.controls_hash
    assert a.input_components.template_hash != b.input_components.template_hash


def test_catalog_version_participates_in_the_composite():
    controls = [control("AAA-01")]
    a = compute_fingerprint(controls, "s", "u", catalog_version="2026.2")
    b = compute_fingerprint(controls, "s", "u", catalog_version="2026.3")
    assert a.input_fingerprint != b.input_fingerprint
    # The controls themselves did not move -- only the catalog stamp.
    assert a.input_components.controls_hash == b.input_components.controls_hash


def test_components_record_control_ids_sorted():
    result = compute_fingerprint([control("ZZZ-09"), control("AAA-01")], "s", "u")
    assert result.input_components.control_ids == ["AAA-01", "ZZZ-09"]
    assert result.input_components.control_count == 2


def test_describe_change_names_added_and_removed_controls():
    before = compute_fingerprint([control("AAA-01")], "s", "u")
    after = compute_fingerprint([control("AAA-01"), control("BBB-02")], "s", "u")
    reasons = describe_change(before.input_components.to_dict(), after.input_components)
    assert any("added" in r for r in reasons)


def test_describe_change_reports_catalog_upgrade():
    before = compute_fingerprint([control("AAA-01")], "s", "u", catalog_version="2026.2")
    after = compute_fingerprint([control("AAA-01")], "s", "u", catalog_version="2026.3")
    reasons = describe_change(before.input_components.to_dict(), after.input_components)
    assert any("catalog" in r for r in reasons)


def test_describe_change_on_first_generation():
    result = compute_fingerprint([control("AAA-01")], "s", "u")
    assert describe_change({}, result.input_components) == ["first generation"]


# ---------------------------------------------------------------------------
# Cross-implementation parity
# ---------------------------------------------------------------------------
#
# These digests were produced by running ``computeControlsFingerprint`` from
# scf-doc-gen ``src/meta/fingerprint.ts`` (bun) over the fixture below. They are
# the contract between the two implementations: a document generated by the CLI
# and imported into the platform must not appear stale on its first run.
#
# If this test fails, the Python canonical form has drifted from the TypeScript
# one. Do not update the constants to match — find what changed. The usual
# culprit is a key rename in ``_canonical_control`` (the key names are hashed) or
# a change to the JSON separators.

_TS_CONTROLS_HASH = "7f6e407cecee7d8718f0706f34667c9b2b2bceb3673fc2f40524675228783a53"
_TS_TEMPLATE_HASH = "0efc543235015b9f5276fc1f88e1cf86280d97a7d818a900fa0355a685b969ef"
_TS_PROMPT_HASH = "512a356516e4b5d13dc4051cf2b93739fac1b9034575b6564f17744bf8543b3a"
_TS_COMPOSITE = "e5451b492be5fad5d012df84f7e28de3960f348a1e2ecb7844e85217453cd047"

_PARITY_SYSTEM_PROMPT = "You are a compliance documentation generator.\nWrite in UK English."
_PARITY_USER_PROMPT = "Generate the IAC domain policy.\n\nControls: IAC-01, AST-02"

_PARITY_CONTROLS = [
    {
        "scf_id": "IAC-01",
        "control_name": "Identity & Access Management",
        "control_description": "Mechanisms exist to facilitate IAM.",
        "implementation_status": "implemented",
        "maturity_level": "L3",
        "owner": "Head of Security",
        "implementation_notes": "JumpCloud enforces SSO + MFA.",
        "assessment_objectives": [
            {"ao_id": "IAC-01-AO2", "objective_text": "Roles are reviewed quarterly."},
            {"ao_id": "IAC-01-AO1", "objective_text": "An IAM policy is documented."},
        ],
    },
    {
        "scf_id": "AST-02",
        "control_name": "Asset Inventory",
        "control_description": "Mechanisms exist to inventory assets.",
        "implementation_status": "monitored",
        "maturity_level": None,
        "owner": None,
        "implementation_notes": None,
        "assessment_objectives": [],
    },
]


def test_matches_typescript_implementation():
    """Byte-for-byte parity with scf-doc-gen when no catalog version is supplied."""
    result = compute_fingerprint(
        _PARITY_CONTROLS, _PARITY_SYSTEM_PROMPT, _PARITY_USER_PROMPT
    )
    assert result.input_components.controls_hash == _TS_CONTROLS_HASH
    assert result.input_components.template_hash == _TS_TEMPLATE_HASH
    assert result.input_components.prompt_hash == _TS_PROMPT_HASH
    assert result.input_fingerprint == _TS_COMPOSITE


def test_control_order_does_not_affect_typescript_parity():
    """The TypeScript side sorts by scf_id too, so input order is irrelevant."""
    reversed_input = list(reversed(_PARITY_CONTROLS))
    result = compute_fingerprint(
        reversed_input, _PARITY_SYSTEM_PROMPT, _PARITY_USER_PROMPT
    )
    assert result.input_fingerprint == _TS_COMPOSITE
    assert result.input_components.control_ids == ["AST-02", "IAC-01"]


def test_catalog_version_is_the_only_deliberate_divergence():
    """Adding a catalog version changes the composite but no component hash.

    This is spec R6: a catalog upgrade that only adds out-of-scope controls must
    still mark the document stale. Component hashes stay comparable across the
    two implementations so ``describe_change`` can still attribute the cause.
    """
    without = compute_fingerprint(
        _PARITY_CONTROLS, _PARITY_SYSTEM_PROMPT, _PARITY_USER_PROMPT
    )
    with_catalog = compute_fingerprint(
        _PARITY_CONTROLS,
        _PARITY_SYSTEM_PROMPT,
        _PARITY_USER_PROMPT,
        catalog_version="2025.3",
    )
    assert with_catalog.input_fingerprint != without.input_fingerprint
    assert with_catalog.input_components.controls_hash == _TS_CONTROLS_HASH
    assert with_catalog.input_components.template_hash == _TS_TEMPLATE_HASH
    assert with_catalog.input_components.prompt_hash == _TS_PROMPT_HASH
